{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-manager.secretName" . }}
  labels:
    {{- include "ldap-manager.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets.env }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
